[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/contracts=lib/openzeppelin-contracts/contracts"]
optimizer = true

ffi = false #to run commands like minting, it's better to leave it on false
fs_permissions = [{access = "read", path = "./img/"}, {access = "read", path = "./broadcast/"}]

# ffi = true #to run commands like minting, it's better to leave it on false
# fs_permissions = [{access = "read", path = "./img/"}, {access = "read", path = "./broadcast/"}]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
